name: Android Pull Request CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  unit-test:
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.ankitverma123 }}
          password: ${{ secrets.dckr_pat_o1hx2Y1vNz3Q0mMb630t8YjXmKY }}

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Run unit test cases
        run: ./gradlew test
      
      - name: Upload unit test cases report
        uses: actions/upload-artifact@v3
        with:
          name: unit_test_cases_report
          path: app/build/reports/tests/testDebugUnitTest/
